id: ACCA6AAF3
title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret Pith
  Instructions on Attaining Vajra Longevity'
type: translation
pechas:
- I8F84E4F0
- IC9334738
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:49:51.909333
  last_modified_at: 2023-01-04 11:49:51.909337
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8F84E4F0/B9F8: 888C
  IC9334738/DC74: 888C
